# Generated by Django 6.0.4 on 2026-05-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papeleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('tramo', models.CharField(max_length=100)),
            ],
        ),
    ]
