# Generated by Django 6.0.4 on 2026-07-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesional', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='papeleta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
