# Generated by Django 6.0.4 on 2026-05-01 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=200)),
                ('tipo_evento', models.CharField(choices=[('CULTO', 'Culto'), ('ENSAYO', 'Ensayo'), ('REUNION', 'Reunión'), ('PRIOSTIA', 'Priostía')], max_length=20)),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='eventos.evento')),
            ],
        ),
    ]
