# Generated by Django 6.0.4 on 2026-05-01 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('hermanos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='hermano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='hermanos.hermano'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('hermano', 'evento')},
        ),
    ]
