# Generated by Django 6.0.4 on 2026-05-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('leido', 'Leído'), ('respondido', 'Respondido')], default='enviado', max_length=20)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
