# Generated by Django 6.0.4 on 2026-05-01 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunicaciones', '0001_initial'),
        ('hermanos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='hermano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='hermanos.hermano'),
        ),
    ]
