# Generated by Django 6.0.4 on 2026-05-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hermano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('numero_hermano', models.PositiveIntegerField(unique=True)),
                ('estado_cuota', models.CharField(choices=[('PAGADO', 'Pagado'), ('NO_PAGADO', 'No pagado')], default='NO_PAGADO', max_length=20)),
                ('caracter', models.CharField(blank=True, choices=[('NAZARENO', 'Nazareno'), ('COSTALERO', 'Costalero'), ('MIEMBRO_JUNTA', 'Miembro de Junta')], max_length=20)),
            ],
        ),
    ]
