# Generated by Django 6.0.4 on 2026-05-01 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hermanos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=255)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publicaciones/')),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='hermanos.hermano')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
