# Generated by Django 6.0.4 on 2026-05-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_objeto', models.CharField(choices=[('IMAGEN', 'Imagen devocional'), ('ENSER', 'Enser'), ('UTIL', 'Útil')], max_length=10)),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('fecha_ultima_restauracion', models.DateField(blank=True, null=True)),
                ('conservacion', models.CharField(blank=True, max_length=255)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_objeto', models.CharField(choices=[('IMAGEN', 'Imagen devocional'), ('ENSER', 'Enser'), ('UTIL', 'Útil')], max_length=10)),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('fecha_ultima_restauracion', models.DateField(blank=True, null=True)),
                ('conservacion', models.CharField(blank=True, max_length=255)),
                ('lugar_culto', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Util',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_objeto', models.CharField(choices=[('IMAGEN', 'Imagen devocional'), ('ENSER', 'Enser'), ('UTIL', 'Útil')], max_length=10)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
